version: '2'

services:
  web:
    build: .
    networks:
      - web
      - default
    container_name: "tufingadmin_nginx_uwsgi_django"
    volumes:
      - ./app:/home/docker/code/app/
      - ./static:/home/docker/volatile/static
      - ./media:/home/docker/persistent/media
    labels:
      - 'traefik.backend=nginx'
      - 'traefik.port=80'
      - "traefik.docker.network=web"
      - 'traefik.enable=true'
      - 'traefik.default.protocol=http'
      - 'traefik.frontend.rule=Host:tuffingadmin.localhost'

  db:
   image: mdillon/postgis:9.6-alpine
   environment:
     POSTGRES_PASSWORD: django
     POSTGRES_DB: django
     POSTGRES_USER: django
   volumes:
     - ./database/initdb:/docker-entrypoint-initdb.d # Place init file(s) here.
     - ./database/pgdata:/var/lib/postgresql/data # I want to manage volumes manually.
   labels:
     - "traefik.enable=false"


  traefik:
    image: traefik
    restart: always
    command: -c /dev/null --web --docker --logLevel=ERROR
    ports:
      - '80:80'
      - '8080:8080'
    networks:
      - web
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
#      - ./traefik.toml:/traefik.toml
#      - ./acme.json:/acme.json
    container_name: traefik


  portainer:
    image: portainer/portainer
    command: --no-auth -H unix:///var/run/docker.sock
    networks:
      - web
      - default
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    labels:
      - 'traefik.backend=portainer'
      - 'traefik.port=9000'
      - 'traefik.frontend.rule=Host:portainer.localhost'
      - "traefik.docker.network=web"

networks:
  web:
    external: true
