# Generated by Django 2.1.1 on 2018-10-17 08:49

from django.db import migrations
import markdownx.models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20181017_0831'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='body',
            field=markdownx.models.MarkdownxField(),
        ),
    ]
