# Generated by Django 2.1.1 on 2018-10-18 08:26

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        #('blog', '0003_auto_20181017_0849'),
        ('blog', '0002_auto_20181017_0831'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='body',
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
    ]
