# Generated by Django 2.1.1 on 2018-10-26 08:55

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20181025_0510'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='teaser',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True),
        ),
    ]
