# Generated by Django 2.1.1 on 2018-10-28 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_article_header_image_small'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='header_image_small',
            field=models.FileField(null=True, upload_to='banners_small/%Y/%m/%d/'),
        ),
    ]
